name: Sample Scheduler
version: v0.1.0
category: Framework
description: A sample scheduler plugin for Rancher.
projectURL: https://github.com/cjellick/sample-scheduler
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm,kubernetes'
