.catalog:
  name: "Etcd"
  version: "2.2.1-rancher1"
  description: |
    Distributed reliable key-value store
  uuid: etcd-0
  questions:
    - variable: "scale"
      description: "Number of Etcd nodes"
      label: "Number of Nodes:"
      required: true
      default: 1
      type: "int"
etcd:
  scale: "${scale}"
